"""
Airtable setup script.

Connects to the configured Airtable base, checks which of the 10
required tables already exist, and creates any that are missing using
the Airtable Web API (via pyairtable's ``Base.create_table``).

Run:
    python -m scripts.setup_airtable          (from project root)
    python scripts/setup_airtable.py          (direct)
"""

from __future__ import annotations

import logging
import sys

from pyairtable import Api

# Allow running both as ``python scripts/setup_airtable.py`` and
# ``python -m scripts.setup_airtable`` from the project root.
sys.path.insert(0, ".")

from app.config import get_settings  # noqa: E402

logger = logging.getLogger(__name__)

# ── Schema definitions ───────────────────────────────────────────────────────
# Each entry is (table_name, description, list_of_field_dicts).
# Field dicts follow the Airtable field model:
#   https://airtable.com/developers/web/api/field-model

_FIELD_TEXT = "singleLineText"
_FIELD_LONG = "multilineText"
_FIELD_NUM = "number"
_FIELD_DATE = "date"
_FIELD_DT = "dateTime"
_FIELD_CHECK = "checkbox"


def _text(name: str) -> dict:
    return {"name": name, "type": _FIELD_TEXT}


def _long(name: str) -> dict:
    return {"name": name, "type": _FIELD_LONG}


def _num(name: str, precision: int = 4) -> dict:
    return {
        "name": name,
        "type": _FIELD_NUM,
        "options": {"precision": precision},
    }


def _date(name: str) -> dict:
    return {
        "name": name,
        "type": _FIELD_DATE,
        "options": {"dateFormat": {"name": "iso"}},
    }


def _datetime(name: str) -> dict:
    return {
        "name": name,
        "type": _FIELD_DT,
        "options": {
            "dateFormat": {"name": "iso"},
            "timeFormat": {"name": "24hour"},
            "timeZone": "utc",
        },
    }


def _checkbox(name: str) -> dict:
    return {
        "name": name,
        "type": _FIELD_CHECK,
        "options": {"icon": "check", "color": "greenBright"},
    }


TABLE_SCHEMAS: list[tuple[str, str, list[dict]]] = [
    (
        "daily_metrics",
        "Campaign-level daily performance data from all networks.",
        [
            _date("date"),
            _text("network"),
            _text("campaign_id"),
            _text("campaign_name"),
            _text("os"),
            _text("country"),
            _num("spend"),
            _num("installs", 0),
            _num("impressions", 0),
            _num("clicks", 0),
            _num("cpi"),
            _num("ipm"),
            _num("ctr"),
            _num("roas_d1"),
            _num("roas_d7"),
            _num("roas_d30"),
            _num("revenue_d1"),
            _num("revenue_d7"),
            _num("revenue_d30"),
        ],
    ),
    (
        "creative_performance",
        "Creative-level performance snapshots for fatigue analysis.",
        [
            _date("date"),
            _text("creative_id"),
            _text("creative_name"),
            _text("concept_tag"),
            _text("platform"),
            _num("ipm"),
            _num("ctr"),
            _num("roas_d7"),
            _num("spend"),
            _num("impressions", 0),
            _num("installs", 0),
            _num("fatigue_score"),
            _num("days_live", 0),
            _num("fatigue_curve_slope"),
        ],
    ),
    (
        "waterfall_state",
        "MAX mediation waterfall state per network/geo/format.",
        [
            _date("date"),
            _text("network"),
            _text("geo_tier"),
            _text("ad_format"),
            _num("floor_price"),
            _num("ecpm"),
            _num("fill_rate"),
            _num("show_rate"),
            _num("revenue"),
            _text("time_block"),
        ],
    ),
    (
        "alert_log",
        "Every alert generated by the intelligence modules.",
        [
            _text("alert_id"),
            _text("type"),
            _text("severity"),
            _text("title"),
            _long("body"),
            _text("channel_delivered"),
            _datetime("timestamp"),
            _text("related_campaign"),
            _num("confidence"),
            _checkbox("acted_on"),
        ],
    ),
    (
        "feedback_log",
        "User feedback (Slack reactions, actions) on alerts.",
        [
            _text("alert_id"),
            _text("reaction"),
            _datetime("timestamp"),
            _text("action_taken"),
            _long("notes"),
        ],
    ),
    (
        "learning_weights",
        "Adaptive weights per alert type updated by the feedback loop.",
        [
            _text("alert_type"),
            _num("weight"),
            _datetime("last_updated"),
            _num("feedback_count", 0),
            _num("positive_rate"),
        ],
    ),
    (
        "email_context",
        "Extracted insights from Gmail messages related to campaigns.",
        [
            _text("email_id"),
            _text("sender"),
            _text("subject"),
            _long("extracted_insights"),
            _text("related_campaign"),
            _date("date"),
            _text("category"),
        ],
    ),
    (
        "slack_context",
        "Summarised Slack thread context linked to campaigns.",
        [
            _text("thread_id"),
            _text("channel"),
            _long("summary"),
            _text("related_campaigns"),
            _date("date"),
        ],
    ),
    (
        "budget_curves",
        "Marginal ROAS curves per network for budget optimisation.",
        [
            _text("network"),
            _date("date"),
            _num("spend_level"),
            _num("marginal_roas"),
            _num("confidence"),
            _text("recommended_action"),
        ],
    ),
    (
        "concept_taxonomy",
        "Creative concept taxonomy with lifetime performance stats.",
        [
            _text("concept_id"),
            _text("concept_name"),
            _long("variations"),
            _text("platforms"),
            _num("avg_roas"),
            _num("total_spend"),
            _text("status"),
        ],
    ),
]


# ── Main logic ───────────────────────────────────────────────────────────────

def main() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s  %(levelname)-8s  %(message)s",
    )

    cfg = get_settings()
    api_key = cfg.airtable_api_key
    base_id = cfg.airtable_base_id

    if not api_key or not base_id:
        print("ERROR: Set AIRTABLE_API_KEY and AIRTABLE_BASE_ID in .env")
        sys.exit(1)

    api = Api(api_key)
    print(f"Connecting to Airtable base {base_id} …")

    # ── Discover existing tables ──────────────────────────────────────────
    try:
        base = api.base(base_id, validate=True)
        schema = base.schema()
        existing = {t.name for t in schema.tables}
        print(f"Base contains {len(existing)} table(s): {sorted(existing)}")
    except Exception as exc:
        print(f"Failed to connect to base: {exc}")
        print()
        _print_manual_instructions()
        sys.exit(1)

    # ── Create missing tables ─────────────────────────────────────────────
    required = {name for name, _, _ in TABLE_SCHEMAS}
    missing = required - existing
    already = required & existing

    if already:
        print(f"\nAlready exist ({len(already)}):")
        for name in sorted(already):
            print(f"  ✓ {name}")

    if not missing:
        print("\nAll 10 tables are present — nothing to create.")
        return

    print(f"\nMissing ({len(missing)}):")
    for name in sorted(missing):
        print(f"  ✗ {name}")

    print("\nCreating missing tables …")
    created = 0
    failed: list[tuple[str, str]] = []

    for table_name, description, fields in TABLE_SCHEMAS:
        if table_name not in missing:
            continue
        try:
            base.create_table(table_name, fields=fields, description=description)
            print(f"  ✓ Created: {table_name}")
            created += 1
        except Exception as exc:
            err = str(exc)
            print(f"  ✗ Failed:  {table_name} — {err}")
            failed.append((table_name, err))

    print(f"\nDone: {created} created, {len(failed)} failed.")

    if failed:
        print("\nSome tables could not be created automatically.")
        _print_manual_instructions(only=failed)


def _print_manual_instructions(
    only: list[tuple[str, str]] | None = None,
) -> None:
    """Print step-by-step manual creation guide."""
    print("\n" + "=" * 60)
    print("MANUAL TABLE CREATION GUIDE")
    print("=" * 60)
    print()
    print("If the Airtable API cannot create tables (permission or plan")
    print("limits), create them manually in the Airtable web UI:")
    print()
    print("  1. Open https://airtable.com and navigate to your base.")
    print("  2. For each table listed below, click '+' to add a new table.")
    print("  3. Name it exactly as shown (case-sensitive).")
    print("  4. Add the fields with the types indicated.")
    print()

    tables = (
        [(name, err) for name, err in only]
        if only
        else [(name, "") for name, _, _ in TABLE_SCHEMAS]
    )
    for table_name, _ in tables:
        # Find matching schema
        for name, desc, fields in TABLE_SCHEMAS:
            if name == table_name:
                print(f"  TABLE: {name}")
                print(f"    {desc}")
                for fld in fields:
                    ftype = fld["type"]
                    readable = {
                        "singleLineText": "text",
                        "multilineText": "long text",
                        "number": "number",
                        "date": "date",
                        "dateTime": "datetime",
                        "checkbox": "checkbox",
                    }.get(ftype, ftype)
                    print(f"      • {fld['name']:25s} ({readable})")
                print()
                break


if __name__ == "__main__":
    main()
