"""
Pydantic models for every data shape used across the application.

Covers normalised campaign / creative / waterfall metrics, alert and
feedback records, daily & creative briefs, and budget recommendations.
"""

from datetime import date as _date
from datetime import datetime as _datetime
from enum import Enum
from typing import Optional, Union

from pydantic import BaseModel, Field


# ── Enums ────────────────────────────────────────────────────────────────────

class Severity(str, Enum):
    low = "low"
    medium = "medium"
    high = "high"
    critical = "critical"


class AlertType(str, Enum):
    anomaly = "anomaly"
    creative_fatigue = "creative_fatigue"
    budget = "budget"
    waterfall = "waterfall"
    system = "system"


class CreativeStatus(str, Enum):
    active = "active"
    fatigued = "fatigued"
    paused = "paused"
    retired = "retired"


# ── Core metric models ───────────────────────────────────────────────────────

class CampaignMetric(BaseModel):
    """Normalised row of campaign-level performance data."""
    date: Union[_date, None] = None
    network: str = ""
    campaign_id: str = ""
    campaign_name: str = ""
    os: str = ""
    country: str = ""
    spend: float = 0.0
    installs: int = 0
    impressions: int = 0
    clicks: int = 0
    cpi: float = 0.0
    ipm: float = 0.0
    ctr: float = 0.0
    roas_d1: float = 0.0
    roas_d7: float = 0.0
    roas_d30: float = 0.0
    revenue_d1: float = 0.0
    revenue_d7: float = 0.0
    revenue_d30: float = 0.0


class CreativeMetric(BaseModel):
    """Per-creative performance snapshot used by the fatigue analyser."""
    creative_id: str = ""
    concept_tag: str = ""
    platform: str = ""
    ipm: float = 0.0
    ctr: float = 0.0
    roas_d7: float = 0.0
    spend: float = 0.0
    impressions: int = 0
    installs: int = 0
    fatigue_score: float = 0.0
    days_live: int = 0
    fatigue_curve_slope: float = 0.0


class WaterfallInstance(BaseModel):
    """Single waterfall entry for a network × geo × ad-format combination."""
    network: str = ""
    geo_tier: str = ""
    ad_format: str = ""
    floor_price: float = 0.0
    ecpm: float = 0.0
    fill_rate: float = 0.0
    show_rate: float = 0.0
    revenue: float = 0.0
    date: Union[_date, None] = None
    time_block: str = ""


# ── Alerts & feedback ────────────────────────────────────────────────────────

class Alert(BaseModel):
    """An alert generated by any intelligence module."""
    alert_id: str = ""
    alert_type: AlertType = AlertType.anomaly
    severity: Severity = Severity.medium
    title: str = ""
    body: str = ""
    channel_delivered: str = ""
    timestamp: Union[_datetime, None] = None
    related_campaign: str = ""
    confidence: float = 0.0


class FeedbackEntry(BaseModel):
    """User feedback on a previously delivered alert."""
    alert_id: str = ""
    reaction: str = ""
    timestamp: Union[_datetime, None] = None
    action_taken: str = ""


# ── Briefs ───────────────────────────────────────────────────────────────────

class DailyBrief(BaseModel):
    """Assembled payload for the morning intelligence brief."""
    date: Union[_date, None] = None
    spend_summary: dict = Field(default_factory=dict)
    roas_tracker: dict = Field(default_factory=dict)
    action_items: list[str] = Field(default_factory=list)
    inbox_context: list[str] = Field(default_factory=list)
    system_confidence: float = 0.0
    raw_data: dict = Field(default_factory=dict)


class CreativeBrief(BaseModel):
    """Summary brief for a creative concept."""
    concept_name: str = ""
    status: CreativeStatus = CreativeStatus.active
    platforms_affected: list[str] = Field(default_factory=list)
    what_worked: str = ""
    recommendations: list[str] = Field(default_factory=list)
    reference_assets: list[str] = Field(default_factory=list)


# ── Budget ───────────────────────────────────────────────────────────────────

class BudgetRecommendation(BaseModel):
    """Recommended budget reallocation for a single network."""
    network: str = ""
    current_spend: float = 0.0
    recommended_spend: float = 0.0
    current_marginal_roas: float = 0.0
    projected_marginal_roas: float = 0.0
    confidence: float = 0.0
